### ISSUE TITLE
How to open terminus Browser in Linux machine

### ISSUE THREAD

**Issue by mrajeshrdy** [terminusdb/terminus-quickstart#1]

**Comment by mrajeshrdy** [comment]
Hi Team,

I am new to linux and I was installed terminus and faceing issue in opening the browser can any one help on this 

Thanks 
Rajesh

**Comment by dmytri** [comment]
Once you start the container by typing:
`./terminus-container run`
in the directory in which you cloned this repo, you should be able to just go to this click this link:

http://localhost:6363

If you are having trouble, please join our Discord server here: https://discord.gg/ufUhbxg

We'll be happy to help you!

**Comment by mrajeshrdy** [comment]
I am running in AWS EC2 machine there is no any gui to open browser and I am connecting through Putty
how to open browser there?

**Comment by rrooij** [comment]
@mrajeshrdy You can run the browser on your own local machine. The Amazon EC2 instance should be the one that hosts it.

**Comment by jbs123** [comment]
I am having same issues. I would like to run everything on an EC2 and just connect with my browser. It doesn't allow though or I have yet to figure out the combination of ENV settings. I just run it normally and tunnel to the machine to get around for now.

**Comment by rrooij** [comment]
@jbs123 Did you set the public url env variable to the URL where the EC2 host is reachable?
