### ISSUE TITLE
Error: API Error url: http://localhost:6363/

### ISSUE THREAD

**Issue by mrajeshrdy** [terminusdb/terminus-quickstart#2]
Hi Team,

What is API Error url and when I was trying to open terminus browser it is asking Key: Server API key 

what i need to provide that and where i find key 

Thanks,
Rajesh
![Terminus_API error](https://user-images.githubusercontent.com/48939446/79833350-d6e12a80-83c8-11ea-936b-9a52c3bf5e24.PNG)

**Comment by spl** [comment]
@mrajeshrdy I ran into something like this when I first tried a few months ago. I think I had to do `./terminus-container rm-config` (or possibly `./terminus-container rm`) to fix it. Does that work for you?

**Comment by rrooij** [comment]
I think we solved this already if I'm not mistaken. Feel free to reopen this if it hasn't been solved.
